overrides:
  vite: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
  sharp: true
