/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    'intro',
    {
      type: 'category',
      label: 'Current Campaigns',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'current' }],
    },
    {
      type: 'category',
      label: 'Previous Campaigns',
      items: [{ type: 'autogenerated', dirName: 'previous' }],
    },
  ],
};
