# This is a basic workflow to help you get started with Actions
name: Node.js CI

permissions:
  contents: read

# Controls when the action will run.
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, labeled]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [lts]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true

      - name: Build
        run: vp run build

      - name: Check
        run: vp check

      - name: Lint Markdown
        run: vp run markdownlint
